### ISSUE TITLE
Barre de statut / connexion & inscription

### ISSUE THREAD

**Issue by mindtech007** [mindtech007/mindtech-forum#10]
on aimerait portée quelques petits sur cette partie. en connectant ou inscrivant sur le forum on reste scotcher sur l'en-tête du site. 

on aimerait qu'une fois connecter ou valider un inscription que le site te mène dans la barre de statut pour pouvoir reperer ou tu dois passer pour acceder a votre compte. et aussi une fois valider on te demandera de completer votre porifl ou on peut ignorer cette partie pour le faire un peu plus tard.  puis acceder directement sur votre compte.

**Comment by arjest** [comment]
Je comprends pas

**Comment by mindtech007** [comment]
ok, normalman lew konekte antet lan chanje men ou pa remake kote pou al sou profil ou. bon, map tou chanjel. ou raplew bouton vert ou te mete avan, wap remetel men pa menm jan an. ou we janw afiche sous-categorie yo nan yon ti cercle gris e menm jan an ou pral metel, wap met ladann foto an ak pseudo an, wap retire dropdown nan ki gen bouton deconnexion an. 

mwen ta renmen une fois moun nan finn esnskri poul tou tonbe nan compte li an, kap mandel poul konplete profil li. apres la al sou paj d'acceuil lan
